In [93]:
# Mounting the Google Drive to access to access files/dataset
from google.colab import drive

In [94]:
# Python version
import sys

print('Python: {}'.format(sys.version))

Python: 3.12.13 (main, Mar  4 2026, 09:23:07) [GCC 11.4.0]

In [95]:
# Importing libaries needed
import pandas as pd

In [96]:
# Assigning the dataset,EmergencyTriageDataset_Reduced_Dirty.csv, to a variable
FILE_PATH= '/content/drive/MyDrive/Colab Notebooks/CariSurg_Triage_Test/EmergencyTriageDataset_Reduced_Dirty.csv'

# Reading the file dataset
raw_data = pd.read_csv(FILE_PATH)

print(f"Dataset loaded: {raw_data.shape[0]} rows x {raw_data.shape[1]} columns")
print(f"Columns: {list(raw_data.columns)}")

Dataset loaded: 2205 rows x 11 columns
Columns: ['ID', 'Age', 'Gender', 'GCS', 'SBP', 'DBP', 'MAP', 'pulse', 'Temp', 'RR', 'Fio2']

In [97]:
# The first 5 rows of the dataset
raw_data.head(5)

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20    Male  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77  Female  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86  FEMALE  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0

In [98]:
# Printing the datatype for only gender right now
print("Data type for the column Gender is", raw_data['Gender'].dtypes)
print("The unique values in Gender are:" + str(raw_data['Gender'].unique()))
print("The total amount of unique values are:", len(raw_data['Gender'].unique()))

Data type for the column Gender is object
The unique values in Gender are:['0' 'Male' 'Female' 'FEMALE' '1' 'MALE']
The total amount of unique values are: 6

In [99]:
# Counting how many of each unique value there is in the dataset

print("Unique Gender values and their counts:")
print(raw_data['Gender'].value_counts())

Unique Gender values and their counts:
Gender
1         422
MALE      379
Male      375
FEMALE    366
Female    340
0         323
Name: count, dtype: int64

In [100]:
gender_mapping = {'female': 0, '0':0, 'male':1, '1':1}

# Stripping of the data and making them lower case and then assigning the new data to a new column
raw_data['Gender_Clean'] = raw_data['Gender'].astype(str).str.lower().str.strip().map(gender_mapping)

print(raw_data['Gender_Clean'].value_counts())

# Checking to see if there any data that did not get mapped
print("NaNs:", raw_data['Gender_Clean'].isnull().sum())

# Dropping the original 'Gender' column
raw_data = raw_data.drop(columns=['Gender'])

# Renaming 'Gender_Clean' to 'Gender'
raw_data = raw_data.rename(columns={'Gender_Clean': 'Gender'})

# Reordering columns to place the new 'Gender' column at index 2 (its original position)
cols = raw_data.columns.tolist()

# Removing 'Gender' from its current position (it's likely at the end now)
cols.remove('Gender')

# Inserting 'Gender' at the desired index (2)
cols.insert(2, 'Gender')

# Reindexing the DataFrame with the new column order
raw_data = raw_data[cols]
print("")
raw_data.head()

Gender_Clean
1    1176
0    1029
Name: count, dtype: int64
NaNs: 0

   ID  Age  Gender   GCS  SBP    DBP     MAP  pulse  Temp    RR   Fio2
0   1   34       0  15.0   93   67.0   75.67  128.0  36.8  14.0   21.0
1   2   20       1  15.0  130   90.0  103.33   80.0  37.0  16.0   21.0
2   3   77       0  14.0  163  105.0  124.33   92.0  36.8  18.0   21.0
3   4   23       0   8.0  100   60.0   73.33  100.0  37.0  12.0  100.0
4   5   86       0  15.0  150   90.0  110.00   85.0  37.0  19.0   21.0